name: libuno
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-190.0.dev <3.0.0'

dependencies:
  kalil_adt_annotation: ^3.0.7
  kalil_utils:
  collection:

dev_dependencies:
  adt_generator: ^3.0.5
  build_runner:
  lints: ^2.0.0
  test: ^1.16.0
